### PR TITLE
Techfest18 24

### PR DESCRIPTION
**Pull request by johnkillmer**
Tim/Trevor,

Player register will enter a new record into the DynamoDb.  It  still needs a lot work on the tests and validation front.  Creating the PR in case you want to merge in what I have completed. Otherwise I'll finish it up when I get back from Scotland on the 29th. 

-John

### CODE REVIEW

**Comment by tvattima** [comment]
Thanks John!

**Comment by tvattima** [comment]
John, for consistency, please rename register.py to RegisterPlayer.py. And rename registerTests.py to RegisterPlayerTests.py

**Comment by johnkillmer** [comment]
> John, for consistency, please rename register.py to RegisterPlayer.py. And rename registerTests.py to RegisterPlayerTests.py

Done

**Comment by tnessy** [comment]
LGTM

**Pull request merged**
